### ISSUE TITLE
Error: Extension exceeds max size

### ISSUE THREAD

**Issue by definiteIymaybe** [fujikky/contentful-color-picker-ui-extension#193]
Hi

Got this error when building / uploading the extension:

<img width="949" alt="image" src="https://user-images.githubusercontent.com/16208594/102839658-12c60700-4412-11eb-9e70-9ac128ced307.png">

The extension has been uploaded and I can assign it to a field, but the sourced .js file is empty hence no input / ui is rendered for the field.

**Comment by fujikky** [comment]
Thank you for your report.
I have reproduced the problem and will try to fix it soon.

**Comment by fujikky** [comment]
Fixed in #194! Try pulling the master branch and redeploying it.

**Comment by definiteIymaybe** [comment]
3.5x reduction! Awesome, thank you so much both for the extension and support.
